spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/energy_orders
    username: postgres
    password: Alemo120
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
